language: node_js
node_js:
- '4.0'
- '9.0'
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GxY1n58pDNJWyAqq4DINSoj40rttREj4wXEvuIR0xLXdZA+XdchGYYbWniUJ9GBGIxPjopM+BbFujMiRmXQIeQR60ULk3zu720484gEwWucvwpoEExQNQ5/hi83jLnAkno/a7AYku2b7vlImObk6dogxiTkLKho9tuNPR7wKeMs=
  file:
    - "soundex-code.js"
    - "soundex-code.min.js"
  on:
    tags: true
    node: '9.0'
